### PR TITLE
insert new webpack entries as hash instead of array.

### PR DESCRIPTION
**Pull request by gone369**
webpack has redefined multiple entries as hash. https://webpack.github.io/docs/multiple-entry-points.html. This commit will reallow multiple entries to be inserted as hash and not get an error when new entries are unshifted in.

### CODE REVIEW

**Comment by mmieszek** [comment]
Thanks for the pull request. Could you please resolve the conflicts?

**Comment by gone369** [comment]
merged.

**Comment by cellis** [comment]
@mmieszek Please publish to NPM, it's not possible to use this without using github as package.

**Comment by sahariko** [comment]
Why is this not published to NPM yet?

**Pull request merged**
